config/routes.rb
Demo::Application.routes.draw do
  get "goodnight/goodnight"

  get "say/hello"

  get "say/goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/goodnight_controller.rb
class GoodnightController < ApplicationController

	def goodnight
		@test = 'jeroen'
		
		def say_goodnight(name)
			result = 'Good night,' + name
			return result
		end
	end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@text = 'Jow schoap'
  	@time = Time.now

	@getal = 1+74 
	@tekst = "cow" + "boy"
	@uurlater = 1.hour.from_now
	@files = Dir.glob('*')

      def say_goodnight(name)
        result = 'Good night,' + name
        return result
      end
  end



  def goodbye
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goodnight_helper.rb
module GoodnightHelper
end

app/helpers/say_goodnight_helper.rb
module SayGoodnightHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/goodnight/goodnight.html.erb
<p><%= @test %></p>

<%= say_goodnight('Mary-Ellen') %><br />
<%= say_goodnight('Jeroen') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1><%= @text %></h1>

<p>It is now <%= @time %></p>

<p>
Time to say
<%= link_to "Goodbye", say_goodbye_path %>!
</p>

<p><%= @getal %></p>
<p><%= @tekst %></p>
<p><%= @uurlater %></p>

<ul>
<% for file in @files %>
<li>file name is: <%= file %></li>
<% end %>
</ul>

app/views/say/hello.html.erb
<h1><%= @text %></h1>

<p>It is now <%= @time %></p>

<p>
Time to say
<%= link_to "Goodbye", say_goodbye_path %>!
</p>

<p><%= @getal %></p>
<p><%= @tekst %></p>
<p><%= @uurlater %></p>

<ul>
<% for file in @files %>
<li>file name is: <%= file %></li>
<% end %>
</ul>

<%= say_goodnight('Mary-Ellen') %><br />
<%= say_goodnight('Jeroen') %>